security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_users:
            entity: { class: App\Entity\User, property: email }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: app_users
                login_path: login
                check_path: login
                default_target_path: /backend/logged_in
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: '^/backend', roles: [ROLE_USER,ROLE_ADMIN] }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset_password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

