twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
         cdn_s3: 'https://cale.s3.eu-central-1.amazonaws.com'
         cale_eth_address: '%env(CALE_ETH_ADRESS)%'
         adsense_active: 1
