twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
         cdn_s3: 'https://cale.s3.eu-central-1.amazonaws.com'
         cale_eth_address: '%env(CALE_ETH_ADRESS)%'
         adsense_active: 0
         cale_android: 'https://play.google.com/store/apps/details?id=io.cordova.cale'
         cale_android_apk: 'https://github.com/martinberlin/cale-app/tree/master/releases'
         web_path: '%kernel.root_dir%/../public'