# Security
login:
  path: /login/{_locale}
  controller: App\Controller\SecurityController::login
  defaults:
    _locale: en
  requirements:
    _locale: '%locales%'

# www
home:
  path:       /{_locale}
  controller: App\Controller\HomeController::index
  defaults:
    _locale: en
  requirements:
    _locale: '%locales%'

#bootstrap:
#  path:       /b
#  controller: App\Controller\HomeController::bootstrap

about-cale:
  path:       /about-cale/{_locale}
  controller: App\Controller\HomeController::aboutCale
  defaults:
    _locale: en

displays-eink:
  path:       /eink-displays/{_locale}
  controller: App\Controller\HomeController::einkDisplays
  defaults:
    _locale: en

displays-tft:
  path:       /tft-displays/{_locale}
  controller: App\Controller\HomeController::tftDisplays
  defaults:
    _locale: en

apis:
  path:       /apis/{_locale}
  controller: App\Controller\HomeController::apis
  defaults:
    _locale: en

transparently:
  path:       /built-transparently/{_locale}
  controller: App\Controller\HomeController::transparently
  defaults:
    _locale: en

thanks:
  path:       /thanks/{_locale}
  controller: App\Controller\HomeController::thanks
  defaults:
    _locale: en

privacy-policy:
  path:       /privacy-policy/{_locale}
  controller: App\Controller\HomeController::privacyPolicy
  defaults:
    _locale: en

google-privacy-policy:
  path:       /g-privacy-policy/{_locale}
  controller: App\Controller\HomeController::googlePrivacyPolicy
  defaults:
    _locale: en

impressum:
  path:       /impressum/{_locale}
  controller: App\Controller\HomeController::impressum
  defaults:
    _locale: en

firmware:
  path:       /firmware/{_locale}
  controller: App\Controller\HomeController::firmware
  defaults:
    _locale: en

firmware-t5:
  path:       /firmware-t5/{_locale}
  controller: App\Controller\HomeController::firmwareT5
  defaults:
    _locale: en

firmware-blue:
  path:       /firmware-bluetooth/{_locale}
  controller: App\Controller\HomeController::firmwareBlue
  defaults:
    _locale: en

www_server-architecture:
  path:       /architecture/{_locale}
  controller: App\Controller\HomeController::architecture
  defaults:
    _locale: en

www_service-pricing:
  path:       /pricing/{_locale}
  controller: App\Controller\HomeController::pricing
  defaults:
    _locale: en

www_getting-started:
  path:       /get-started/{_locale}
  controller: App\Controller\HomeController::getStarted
  defaults:
    _locale: en

www_api-ical:
  path:       /api-ical/{_locale}
  controller: App\Controller\HomeController::apiIcal
  defaults:
    _locale: en
www_api-cloudwatch:
  path:       /api-cloudwatch/{_locale}
  controller: App\Controller\HomeController::cloudwatch
  defaults:
    _locale: en