# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # ex.             http://calendar.fasani.de/screenshot/cale.php?u=http://calendar.fasani.de/paulina&w=400&h=300&d=1
    screenshot_host: 'http://calendar.fasani.de'
    screenshot_path: '/cale.php?u=[url]&w=[width]&h=[height]&b=[brightness]&d=[bitdepth]&c=[compressed]&cache=[cache]'
    screenshot_parts: ['url','width','height','brightness','bitdepth','compressed', 'cache']
    api_languages:
        en: English
        de: German
        es: Spanish
        ca: Catalan
        fr: French
        hr: Croatian
        cs: Czech
        da: Danish
        el: Greek
        ar: Arabic
        eo: Esperanto
        et: Estonian
        fi: Finnish
        he: Hebrew
        hi: Hindi
        hu: Hungarian
        id: Indonesian
        is: Icelandic
        it: Italian
        ja: Japanese
        ka: Georgian
        kn: Kannada
        ko: Korean
        lv: Latvian
        ml: Malayam
        mr: Marathi
        nb: Norwegian Bokmål
        nl: Dutch
        no: Norwegian Bokmål (alias for nb)
        pa: Punjabi
        pl: Polish
        pt: Portuguese
        ro: Romanian
        ru: Russian
        sk: Slovak
        sl: Slovenian
        sr: Serbian
        sv: Swedish
        ta: Tamil
        te: Telugu
        tr: Turkish
        uk: Ukrainian
        ur: Urdu
        zh: simplified Chinese

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '../src/Service/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    App\Service\GoogleClientService:
        arguments:
            - \Google_Client
